name: SquidServers WinGet
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  check-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Fetch CDN Metadata
        id: cdn_data
        shell: bash
        run: |
          curl -s https://cdn.squidservers.com/latest.yml -o latest.yml
          VERSION=$(grep '^version:' latest.yml | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Submit to WinGet
        run: |
          dotnet tool install --global Microsoft.WinGet.Create
          wingetcreate submit https://cdn.squidservers.com/squidservers-latest-setup.exe `
            --identifier SquidServers.SquidServers `
            --version ${{ steps.cdn_data.outputs.version }} `
            --token ${{ secrets.WINGET_TOKEN }} `
            --urls https://cdn.squidservers.com/squidservers-latest-setup.exe `
            --interactive $false
